"use strict";
const fs=require("fs"),path=require("path");
function readInput(arg){const raw=arg.startsWith("@")?fs.readFileSync(path.resolve(arg.slice(1)),"utf8"):arg;return JSON.parse(raw.replace(/^\uFEFF/,""));}
function count(value){return Array.from(String(value||"")).length;}
function compact(value){return String(value||"").replace(/\s+/g,"").trim();}
function hasLongVerbatim(summary,source,size=80){const left=compact(summary),right=compact(source);if(left.length<size||right.length<size)return false;for(let i=0;i<=left.length-size;i+=8)if(right.includes(left.slice(i,i+size)))return true;return false;}
function prepare(input){const related=input.related_profile||input;const sources=(related.pages||[]).map((page,index)=>({id:`S${index+1}`,title:page.title,url:page.url,sections:page.sections||[],content:page.content||"",truncated:Number(page.text_length_before_truncation||0)>count(page.content||"")}));return{schema_version:3,character:related.character||{},sources,source_review:sources.map(source=>({id:source.id,reviewed:false,used_for:[],notes:""})),analysis:{background:{summary:"",current_identity:null,key_events:[],current_goals:[],unresolved_threads:[]},soul:{summary:"",core_motivation:null,perception_priorities:[],decision_rules:[],stress_responses:[],trust_patterns:[],vulnerabilities:[],unknowns:[]}},claim_contract:{text:"用自己的话归纳后的声明",basis:"explicit|inferred|unknown",citations:["S1"],evidence:[{citation:"S1",excerpt:"来源中的连续原文证据"}]},synthesis_contract:{read_all_sources:true,do_not_slice_by_prefix_or_fixed_length:true,summarize_in_own_words:true,keep_verbatim_only_in_evidence:true}};}
function validate(input){const sourceMap=new Map((input.sources||[]).map(source=>[source.id,source])),errors=[],warnings=[];let claimCount=0,groundedCount=0;
function inspect(value,pointer){if(Array.isArray(value))return value.forEach((item,index)=>inspect(item,`${pointer}/${index}`));if(!value||typeof value!=="object")return;if(typeof value.text==="string"){claimCount++;const basis=value.basis;if(!["explicit","inferred","unknown"].includes(basis))errors.push(`${pointer}: basis 必须为 explicit、inferred 或 unknown`);const citations=Array.isArray(value.citations)?value.citations:[];if(basis!=="unknown"&&!citations.length)errors.push(`${pointer}: 缺少来源引用`);citations.forEach(id=>{if(!sourceMap.has(id))errors.push(`${pointer}: 未知来源 ${id}`);});const evidence=Array.isArray(value.evidence)?value.evidence:[];if(basis!=="unknown"&&!evidence.length)errors.push(`${pointer}: explicit/inferred 声明必须提供 evidence`);let grounded=basis==="unknown";evidence.forEach((item,index)=>{const source=sourceMap.get(item?.citation),excerpt=String(item?.excerpt||"").trim();if(!source)errors.push(`${pointer}/evidence/${index}: 未知来源 ${item?.citation||"空"}`);else if(!citations.includes(item.citation))errors.push(`${pointer}/evidence/${index}: evidence 来源必须同时列入 citations`);else if(count(excerpt)<8)errors.push(`${pointer}/evidence/${index}: excerpt 至少 8 字符`);else if(!compact(source.content).includes(compact(excerpt)))errors.push(`${pointer}/evidence/${index}: excerpt 无法在 ${item.citation} 原文中定位`);else grounded=true;});if(grounded)groundedCount++;}Object.entries(value).forEach(([key,child])=>{if(!["evidence","citations"].includes(key))inspect(child,`${pointer}/${key}`);});}
inspect(input.analysis||{},"/analysis");const reviews=input.source_review||[],reviewedIds=new Set(reviews.filter(item=>item.reviewed===true).map(item=>item.id));for(const id of sourceMap.keys())if(!reviewedIds.has(id))errors.push(`source_review: ${id} 尚未审阅`);reviews.forEach((item,index)=>{if(!sourceMap.has(item.id))errors.push(`source_review/${index}: 未知来源 ${item.id}`);if(!Array.isArray(item.used_for))errors.push(`source_review/${index}: used_for 必须为数组`);if(!String(item.notes||"").trim())warnings.push(`source_review/${index}: 建议记录该来源的用途或排除原因`);});
const background=String(input.analysis?.background?.summary||"").trim(),soul=String(input.analysis?.soul?.summary||"").trim();const noise=/BWIKI|媒体文件:|获得方式|需完成任务|累积使用|好感度加成|\d+\s*(?:完美|卓越)|技能数值|冷却时间|造成\d+点伤害|角色故事导航|更新改动历史/;const meta=/已核验语音|来源显示|引用显示|根据(?:Wiki|BWIKI|页面|资料)|本角色卡|生成过程/;if(count(background)<260)errors.push("background.summary 至少 260 字符");if(count(soul)<380)errors.push("soul.summary 至少 380 字符");if(noise.test(background)||noise.test(soul))errors.push("summary 混入任务、礼物、技能、媒体或导航噪声");if(meta.test(background)||meta.test(soul))errors.push("summary 混入来源说明或生成过程元话语");if(/角色扮演时|玩家|用户|你应该|应当扮演/.test(soul))errors.push("soul.summary 必须使用第三人称人物描述，不能写扮演指令");for(const source of sourceMap.values()){if(hasLongVerbatim(background,source.content)||hasLongVerbatim(soul,source.content)){errors.push(`summary 与来源“${source.title}”存在至少 80 字连续照抄`);break;}}
const bg=input.analysis?.background||{},sp=input.analysis?.soul||{};if(!bg.current_identity?.text)errors.push("background.current_identity 必填");if((bg.key_events||[]).length<2)errors.push("background.key_events 至少 2 条");if((bg.current_goals||[]).length<1)errors.push("background.current_goals 至少 1 条");if(!(bg.unresolved_threads||[]).length&&!(sp.unknowns||[]).length)errors.push("必须记录至少 1 条未解线索或明确未知项");if(!sp.core_motivation?.text)errors.push("soul.core_motivation 必填");if((sp.perception_priorities||[]).length<1)errors.push("soul.perception_priorities 至少 1 条");if((sp.decision_rules||[]).length<2)errors.push("soul.decision_rules 至少 2 条");if((sp.stress_responses||[]).length<1)errors.push("soul.stress_responses 至少 1 条");if((sp.trust_patterns||[]).length<1)errors.push("soul.trust_patterns 至少 1 条");if((sp.vulnerabilities||[]).length<1)errors.push("soul.vulnerabilities 至少 1 条");if((sp.unknowns||[]).length<1)errors.push("soul.unknowns 至少 1 条，避免无依据补全人格");if(claimCount<12)errors.push("综合分析声明至少 12 条");if(groundedCount!==claimCount)errors.push(`存在未通过证据定位的声明：${groundedCount}/${claimCount}`);return{ok:errors.length===0,schema_version:input.schema_version,claim_count:claimCount,grounded_claim_count:groundedCount,reviewed_source_count:reviewedIds.size,errors,warnings,data:input};}
try{const command=process.argv[2],input=readInput(process.argv[3]);const result=command==="prepare"?prepare(input):command==="validate"?validate(input):(()=>{throw new Error("Command must be prepare or validate");})();process.stdout.write(JSON.stringify(result,null,2));if(result.ok===false)process.exitCode=2;}catch(error){process.stderr.write(`${error.stack||error.message}\n`);process.exitCode=1;}
